server:
  port: 8080
  servlet:
    context-path: /
    jsp:
      init-parameters: true
  tomcat:
    uri-encoding: UTF-8
    basedir: /home/tmp

spring:
  application:
    name: datesource
  mvc:
    view:
      # jsp前缀
      prefix: /WEB-INF/pages/
      # jsp后缀
      suffix: .jsp
      #配置静态资源访问路径
      static-path-pattern: /webapp/**
      #static-path-pattern=/webapp/**
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    upload:
      drive:
        letter: D
      base-path: upload
      extend-path:
        head-path: head
        video-path: video
        pic-path: pic
        ppt-path: ppt
        word-path: word
        excel-path: excel
        other-path: other
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3307/demo_qx?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    druid:
      filters: stat
      initial-size: 2
      max-active: 300
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 200
      validation-query: SELECT 1
      filter:
        log4j2:
          enabled: true



mybatis-plus:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.demo.pojo  # 注意：对应实体类的路径
logging:
  config: classpath:log4j2.xml
  level:
    cn.jay.repository: trace
#pagehelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql